app_id: 5B599538-42B1-4826-A479-AF079F21A65D
publisher: azkadev
publisher_url: https://github.com/azkadev
display_name: Specta App Azkadev
create_desktop_icon: true
install_dir_name: SPECTA-APP
locales:
  - en
  - zh