name: 'example'
description: 'A new Flutter project.'
publish_to: 'none'
version: '0.0.0'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  cupertino_icons: '^1.0.8'
  iconsax: '^0.0.8'
  http: '^0.13.4'
  path_provider: '^2.1.4'
  easy_isolate: '^1.3.0'
  universal_io: '^2.2.2'
  general_lib_flutter: '^0.0.25'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^1.0.0'
  simulate: 
    path: '../'
flutter: 
  uses-material-design: true
dependency_overrides: 
  pointycastle: '3.8.0'
funding: 
  - 'https://github.com/sponsors/azkadev'
