name: 'simulate'
description: 'Simulate application or add device mock on your app or your flutter project suppoer cross platform android ios , linux , macos, windows.'
version: '0.0.41'
homepage: 'https://github.com/azkadev/simulate'
repository: 'https://github.com/azkadev/simulate'
issue_tracker: 'https://github.com/azkadev/simulate/issues'
publish_to: 'none'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  windows: null
  web: null
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  cupertino_icons: '^1.0.8'
  device_frame: '^1.2.0'
  file_picker: '^8.1.3'
  window_manager: '^0.4.0'
  flutter_hicons: '^0.1.0'
  universal_io: '^2.2.2'
  general_lib_flutter: '^0.0.27'
  general_lib: '^0.0.46'
  icons_plus: '^5.0.0'
  system_information: ^0.0.0
  # system_information_flutter: ^0.0.0
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^4.0.0'
flutter: 
  uses-material-design: true
dependency_overrides: 
  pointycastle: '3.8.0'
funding: 
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
documentation: 'https://youtube.com/@azkadev'
