name: 'simulate'
description: 'Simulate application or add device mock on your app or your flutter project suppoer cross platform android ios , linux , macos, windows.'
version: '0.0.54'
repository: 'https://github.com/azkadev/simulate'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  windows: null
  web: null
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: 'flutter'
  cupertino_icons: '^1.0.8'
  device_frame: '^1.2.0'
  file_picker: '^9.0.2'
  window_manager: '^0.4.3'
  io_universe: '^0.0.8'
  general_lib_flutter: '^0.0.42'
  general_lib: '^0.0.71'
  system_information: '^0.0.13'
  general_framework: '^0.0.31'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
flutter:
  uses-material-design: true
dependency_overrides:
  pointycastle: '4.0.0'
  mime: '^2.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
documentation: 'https://youtube.com/@azkadev'
project:
  type: 'library'
